version: "3.8"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/var/www/app/src
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hh
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d